import Head from 'next/head'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Fudo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.png" />
      </Head>

      <main >
        <h1>Heading</h1>
      </main>

      
    </div>
  )
}
